version: "3.8"

services:
  relay:
    container_name: fuse_relay
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: /relay
    environment:
      POST: 2700
      POSTGRESQL_DATABASE: postgres://nostr:nostr@postgres:5432/nostr?sslmode=disable
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 2700:2700

  postgres:
    container_name: fuse_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nostr
      POSTGRES_USER: nostr
      POSTGRES_PASSWORD: nostr
      # allow all connections without a password. This is *not* recommended for prod
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr"] # database username here - nostr, should be changed if other user
      interval: 10s
      timeout: 5s
      retries: 5
